spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/fast_architecture?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
  redis:
      host: 127.0.0.1
      port: 6379
      password:

knife4j:
  # 开启增强配置
  enable: true
  setting:
    # 是否启用 Host
    enable-host: true
    # 启用 Host 地址
    enable-host-text: "http://127.0.0.1:${server.port}"
